// NEXT COMPONENTS
import Head from 'next/head';
import Image from 'next/image';

// COMPONENTS
import Nav from '../components/Nav';
import ServiceCard from '../components/ServiceCard';
import PortfolioCard from '../components/PortfolioCard';
import Testimonial from '../components/Testimonial';
import ProjectInquiry from '../components/ProjectInquiry';
import Footer from '../components/Footer';

// IMAGES
import img1 from '../assets/HeroArea.jpg';
import webDesign from '../assets/web-design.png';
import shoppingOnline from '../assets/shopping-online.png';
import app from '../assets/app.png';
import seo from '../assets/seo.png';
import blogging from '../assets/blogging.png';
import computer from '../assets/computer.png';
import communication from '../assets/communication.png';
import marketing from '../assets/marketing.png';

const service_data = [
  { img: webDesign, title: 'Web Design', key: 0 },
  { img: shoppingOnline, title: 'E-Commerce', key: 1 },
  { img: app, title: 'Mobile Solutions', key: 2 },
  { img: seo, title: 'Custom Development', key: 3 },
  {
    img: blogging,
    title: 'Content Management Systems',
    key: 4,
  },
  { img: computer, title: 'Hosting & Maintenance', key: 5 },
  {
    img: communication,
    title: 'Strategy & Consulting',
    key: 6,
  },
  { img: marketing, title: 'Online Marketing', key: 7 },
];

const portfolio_data = [
  { img: 'assets/real-estate-example.jpg', title: 'Real Estate LLC' },
  { img: 'assets/real-estate-example-2.jpg', title: 'Real Estate Economy' },
  { img: 'assets/real-estate-example3.avif', title: 'Just Real Estate' },
];

const testimonial_data = [
  {
    img: 'assets/jerome.jpg',
    name: 'Jerome Bell',
    position: 'Marketing Coordinator',
  },
  {
    img: 'assets/cody.jpg',
    name: 'Cody Fisher',
    position: 'President of Sales',
  },
  { img: 'assets/robert.jpg', name: 'Robert Fox', position: 'Web Designer' },
];

export default function Start() {
  return (
    <div>
      <Head>
        <title>Web Agency</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <main>
        {/* HERO AREA */}
        <section>
          <div
            style={{ height: '617px' }}
            className='relative h-screen overflow-hidden'
          >
            <Image
              alt='Hero Area'
              src={img1}
              className='absolute object-cover w-full h-full'
            />
            <div className='absolute inset-0 bg-black opacity-25'></div>
            <div className='container relative z-10 flex items-center w-4/5 py-16 mx-auto rounded-lg md:my-32'>
              <div className='relative z-10 flex flex-col items-center w-full'>
                <h1 className='text-5xl font-bold my-5'>
                  Best Agency in The World
                </h1>
                <p>
                  Adipisicing id do aute culpa adipisicing culpa irure ullamco.
                </p>
                <div className='my-5 flex justify-between'>
                  <button
                    type='button'
                    className='inline-block px-6 mx-2.5 py-2.5 bg-blue-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-500 hover:shadow-lg focus:bg-blue-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-600 active:shadow-lg transition duration-150 ease-in-out'
                  >
                    Start Project
                  </button>
                  <button
                    type='button'
                    className='inline-block px-6 mx-2.5 py-2.5 bg-gray-200 text-blue-400 border-blue-400 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-gray-300 hover:shadow-lg focus:bg-gray-300 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-gray-400 active:shadow-lg transition duration-150 ease-in-out'
                  >
                    Learn More
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* SERVICES SECTION */}
        <section>
          <div className='top-section'>
            <h6>Services</h6>
            <h2 className='text-2xl font-bold'>
              Custom E-Commerce, Mobile & Web Application Development
            </h2>
            <p>
              Aliquip cillum culpa cupidatat officia id do commodo mollit id
              cillum elit anim excepteur. Duis magna elit voluptate consequat
              incididunt nostrud fugiat elit in nulla consectetur deserunt ex.
            </p>
          </div>

          <div className='card-container'>
            <div className='top'>
              {service_data.map((e) => {
                return <ServiceCard key={e.key} img={e.img} title={e.title} />;
              })}
            </div>
            <div className='bottom'>
              <div>{/* Card Component */}</div>
              <div>{/* Card Component */}</div>
              <div>{/* Card Component */}</div>
              <div>{/* Card Component */}</div>
            </div>
          </div>
        </section>

        {/* PORTFOLIO SECTION*/}
        <section>
          <div className='top-section'>
            <h6>Portfolio</h6>
            <h2 className='text-2xl font-bold'>Our Recent Works</h2>
            <p>
              Aliquip cillum culpa cupidatat officia id do commodo mollit id
              cillum elit anim excepteur. Duis magna elit voluptate consequat
              incididunt nostrud fugiat elit in nulla consectetur deserunt ex.
            </p>
          </div>

          <div className='bottom-section'>
            <div className='portfolio-container'>
              <div>{/* Project Component */}</div>
              <div>{/* Project Component */}</div>
              <div>{/* Project Component */}</div>
            </div>

            <button className='inline-block px-6 py-2.5 bg-blue-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-500 hover:shadow-lg focus:bg-blue-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-600 active:shadow-lg transition duration-150 ease-in-out'>
              See All Portfolio
            </button>
          </div>
        </section>

        {/* TESTIMONIALS SECTION */}
        <section>
          <div className='top-section'>
            <h2 className='text-2xl font-bold'>Customer Testimonials</h2>
            <p>
              Aliquip cillum culpa cupidatat officia id do commodo mollit id
              cillum elit anim excepteur.
            </p>
          </div>

          <div className='testimonial-container'>
            <div>{/* Testimonial Component */}</div>
            <div>{/* Testimonial Component */}</div>
            <div>{/* Testimonial Component */}</div>
          </div>
        </section>

        {/* PROJECT INQUIRY SECTION */}
        <section>
          <div className='top-section'>
            <div>{/* Left Blue Line */}</div>
            <div>{/* Right Blue Line */}</div>
            <h2 class='text-2xl font-bold'>
              Mobile Solution: Targeted. Optimized. Integrated.
            </h2>
            <p>
              Aliquip cillum culpa cupidatat officia id do commodo mollit id
              cillum elit anim excepteur.
            </p>
          </div>

          <ProjectInquiry />
        </section>

        {/* FAQ SECTION */}
        <section>
          <div className='top-section'>
            <h6>FAQ`s</h6>
            <h2 className='text-2xl font-bold'>Find The Answers You Need</h2>
            <p>
              Aliquip cillum culpa cupidatat officia id do commodo mollit id
              cillum elit anim excepteur.
            </p>
          </div>

          <div className='faq-container'>
            <div>{/* Dropdown Box */}</div>
            <div>{/* Dropdown Box */}</div>
            <div>{/* Dropdown Box */}</div>
            <div>{/* Dropdown Box */}</div>
            <div>{/* Dropdown Box */}</div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
